/**
 * Converte dados do material do formato do banco (snake_case) 
 * para o formato do formulário (camelCase)
 */
export function mapMaterialFromDB(material) {
  if (!material) return null;

  return {
    // Tab 1: Dados Básicos
    material: material.material || '',
    codigoSap: material.codigo_sap || '',
    status: material.status || '',
    matlDesc: material.matl_desc || '',
    indSector: material.ind_sector || '',
    matlType: material.matl_type || '',
    oldMatNo: material.old_mat_no || '',
    stdDescr: material.std_descr || '',
    basicMatl: material.basic_matl || '',
    plRefMat: material.pl_ref_mat || '',
    document: material.document || '',
    langu: material.langu || '',

    // Tab 2: Classificação
    matlGroup: material.matl_group || '',
    extmatlgrp: material.extmatlgrp || '',
    division: material.division || '',
    prodHier: material.prod_hier || '',
    itemCat: material.item_cat || '',
    matGrpSm: material.mat_grp_sm || '',
    purStatus: material.pur_status || '',
    batchMgmt: material.batch_mgmt || false,
    eanUpc: material.ean_upc || '',
    physicalCommodity: material.physical_commodity || false,
    abcId: material.abc_id || '',

    // Tab 3: Unidades e Medidas
    baseUom: material.base_uom || '',
    altUnit: material.alt_unit || '',
    fatorAltUnit: material.fator_alt_unit || '',
    fatorBaseUom: material.fator_base_uom || '',
    grossWt: material.gross_wt || '',
    netWeight: material.net_weight || '',
    unitOfWt: material.unit_of_wt || '',
    volume: material.volume || '',
    volumeunit: material.volumeunit || '',

    // Tab 4: Compras
    plant: material.plant || '',
    purGroup: material.pur_group || '',
    purStatusMarc: material.pur_status_marc || '',
    poUnit: material.po_unit || '',
    autoPOrd: material.auto_p_ord || false,
    purValkey: material.pur_valkey || '',
    poText: material.po_text || '',
    storConds: material.stor_conds || '',
    minremlife: material.minremlife || '',
    shelfLife: material.shelf_life || '',
    periodIndExpirationDate: material.period_ind_expiration_date || '',
    sledBbd: material.sled_bbd || '',

    // Tab 5: Planejamento (MRP)
    mrpType: material.mrp_type || '',
    mrpCtrler: material.mrp_ctrler || '',
    mrpGroup: material.mrp_group || '',
    reorderPt: material.reorder_pt || '',
    lotsizekey: material.lotsizekey || '',
    minlotsize: material.minlotsize || '',
    maxlotsize: material.maxlotsize || '',
    fixedLot: material.fixed_lot || '',
    roundVal: material.round_val || '',
    servLevel: material.serv_level || '',
    maxStock: material.max_stock || '',
    safetyStk: material.safety_stk || '',
    minSafetyStk: material.min_safety_stk || '',
    covprofile: material.covprofile || '',
    bwdCons: material.bwd_cons || '',
    consummode: material.consummode || '',
    fwdCons: material.fwd_cons || '',
    replentime: material.replentime || '',
    depReqId: material.dep_req_id || '',
    planStrgp: material.plan_strgp || '',

    // Tab 6: Produção
    procType: material.proc_type || '',
    spproctype: material.spproctype || '',
    backflush: material.backflush || false,
    jitRelvt: material.jit_relvt || false,
    bulkMat: material.bulk_mat || false,
    batchentry: material.batchentry || '',
    inhseprodt: material.inhseprodt || '',
    plndDelry: material.plnd_delry || '',
    grPrTime: material.gr_pr_time || '',
    ppcPlCal: material.ppc_pl_cal || '',
    smKey: material.sm_key || '',
    assyScrap: material.assy_scrap || '',
    compScrap: material.comp_scrap || '',
    repmanprof: material.repmanprof || '',
    repManuf: material.rep_manuf || '',
    productionScheduler: material.production_scheduler || '',
    prodprof: material.prodprof || '',
    underTol: material.under_tol || '',
    overTol: material.over_tol || '',
    noCosting: material.no_costing || false,
    sernoProf: material.serno_prof || '',
    lotSize: material.lot_size || '',
    specprocty: material.specprocty || '',
    prtUsage: material.prt_usage || '',
    ctrlKey: material.ctrl_key || '',
    dbText: material.db_text || '',

    // Tab 7: Armazenagem
    stgeLoc: material.stge_loc || '',
    ctrlCode: material.ctrl_code || '',
    stgeBin: material.stge_bin || '',
    availcheck: material.availcheck || '',
    transGrp: material.trans_grp || '',
    loadinggrp: material.loadinggrp || '',
    countryori: material.countryori || '',
    profitCtr: material.profit_ctr || '',
    shMatTyp: material.sh_mat_typ || '',
    matCfop: material.mat_cfop || '',
    sdText: material.sd_text || '',
    issStLoc: material.iss_st_loc || '',
    supplyArea: material.supply_area || '',
    slocExprc: material.sloc_exprc || '',

    // Campos do sistema
    createdBy: material.createdBy || material.created_by || '',
    isActive: material.isActive !== undefined ? material.isActive : (material.is_active !== undefined ? material.is_active : true),
    statusIntegracao: material.statusIntegracao || '',

    // Objetos aninhados - Sales Distribution
    salesDistribution: material.sales_distributions?.[0] ? {
      vkorg: material.sales_distributions[0].vkorg || '',
      vtweg: material.sales_distributions[0].vtweg || '',
      spart: material.sales_distributions[0].spart || '',
      dwerk: material.sales_distributions[0].dwerk || '',
      lgort: material.sales_distributions[0].lgort || '',
      prctr: material.sales_distributions[0].prctr || '',
      ktgrm: material.sales_distributions[0].ktgrm || '',
      salesUnit: material.sales_distributions[0].sales_unit || '',
      minOrder: material.sales_distributions[0].min_order || '',
      minDely: material.sales_distributions[0].min_dely || '',
      delyUnit: material.sales_distributions[0].dely_unit || '',
      taxType1: material.sales_distributions[0].tax_type_1 || '',
      taxclass1: material.sales_distributions[0].taxclass_1 || '',
      matlStats: material.sales_distributions[0].matl_stats || '',
      rebateGrp: material.sales_distributions[0].rebate_grp || '',
      commGroup: material.sales_distributions[0].comm_group || '',
      matPrGrp: material.sales_distributions[0].mat_pr_grp || '',
      acctAssgt: material.sales_distributions[0].acct_assgt || '',
      cashDisc: material.sales_distributions[0].cash_disc || '',
      roundProf: material.sales_distributions[0].round_prof || '',
    } : {
      vkorg: '',
      vtweg: '',
      spart: '',
      dwerk: '',
      lgort: '',
      prctr: '',
      ktgrm: '',
      salesUnit: '',
      minOrder: '',
      minDely: '',
      delyUnit: '',
      taxType1: '',
      taxclass1: '',
      matlStats: '',
      rebateGrp: '',
      commGroup: '',
      matPrGrp: '',
      acctAssgt: '',
      cashDisc: '',
      roundProf: '',
    },

    // Objetos aninhados - Controlling
    controlling: material.controllings?.[0] ? {
      bwkey: material.controllings[0].bwkey || '',
      bwtar: material.controllings[0].bwtar || '',
      matKlass: material.controllings[0].mat_klass || '',
      valArea: material.controllings[0].val_area || '',
      valClass: material.controllings[0].val_class || '',
      priceCtrl: material.controllings[0].price_ctrl || '',
      stdPrice: material.controllings[0].std_price || '',
      priceUnit: material.controllings[0].price_unit || '',
      movingPrice: material.controllings[0].moving_price || '',
      priceDate: material.controllings[0].price_date || '',
      mlActive: material.controllings[0].ml_active || false,
      mlSettle: material.controllings[0].ml_settle || false,
      originMat: material.controllings[0].origin_mat || false,
      originGroup: material.controllings[0].origin_group || '',
      overheadGrp: material.controllings[0].overhead_grp || '',
      profitCtr2: material.controllings[0].profit_ctr2 || '',
      qtyStruct: material.controllings[0].qty_struct || false,
      inHouse: material.controllings[0].in_house || false,
      matUsage: material.controllings[0].mat_usage || '',
      plndprice1: material.controllings[0].plndprice1 || '',
      plndprdate1: material.controllings[0].plndprdate1 || '',
      plndprice2: material.controllings[0].plndprice2 || '',
      plndprdate2: material.controllings[0].plndprdate2 || '',
      plndprice3: material.controllings[0].plndprice3 || '',
      plndprdate3: material.controllings[0].plndprdate3 || '',
    } : {
      bwkey: '',
      bwtar: '',
      matKlass: '',
      valArea: '',
      valClass: '',
      priceCtrl: '',
      stdPrice: '',
      priceUnit: '',
      movingPrice: '',
      priceDate: '',
      mlActive: false,
      mlSettle: false,
      originMat: false,
      originGroup: '',
      overheadGrp: '',
      profitCtr2: '',
      qtyStruct: false,
      inHouse: false,
      matUsage: '',
      plndprice1: '',
      plndprdate1: '',
      plndprice2: '',
      plndprdate2: '',
      plndprice3: '',
      plndprdate3: '',
    },

    // Arrays para compatibilidade
    salesDistributions: material.sales_distributions || [],
    controllings: material.controllings || [],
  };
}

/**
 * Converte dados do formulário (camelCase) para o formato do banco (snake_case)
 */
export function mapMaterialToDB(formData) {
  return {
    // Tab 1: Dados Básicos
    material: formData.material,
    codigo_sap: formData.codigoSap || null,
    status: formData.status || null,
    matl_desc: formData.matlDesc || null,
    ind_sector: formData.indSector || null,
    matl_type: formData.matlType || null,
    old_mat_no: formData.oldMatNo || null,
    std_descr: formData.stdDescr || null,
    basic_matl: formData.basicMatl || null,
    pl_ref_mat: formData.plRefMat || null,
    document: formData.document || null,
    langu: formData.langu || null,

    // Tab 2: Classificação
    matl_group: formData.matlGroup || null,
    extmatlgrp: formData.extmatlgrp || null,
    division: formData.division || null,
    prod_hier: formData.prodHier || null,
    item_cat: formData.itemCat || null,
    mat_grp_sm: formData.matGrpSm || null,
    pur_status: formData.purStatus || null,
    batch_mgmt: formData.batchMgmt || null,
    ean_upc: formData.eanUpc || null,
    physical_commodity: formData.physicalCommodity || null,
    abc_id: formData.abcId || null,

    // Tab 3: Unidades e Medidas
    base_uom: formData.baseUom || null,
    alt_unit: formData.altUnit || null,
    fator_alt_unit: formData.fatorAltUnit || null,
    fator_base_uom: formData.fatorBaseUom || null,
    gross_wt: formData.grossWt || null,
    net_weight: formData.netWeight || null,
    unit_of_wt: formData.unitOfWt || null,
    volume: formData.volume || null,
    volumeunit: formData.volumeunit || null,

    // Tab 4: Compras
    plant: formData.plant || null,
    pur_group: formData.purGroup || null,
    pur_status_marc: formData.purStatusMarc || null,
    po_unit: formData.poUnit || null,
    auto_p_ord: formData.autoPOrd || null,
    pur_valkey: formData.purValkey || null,
    po_text: formData.poText || null,
    stor_conds: formData.storConds || null,
    minremlife: formData.minremlife || null,
    shelf_life: formData.shelfLife || null,
    period_ind_expiration_date: formData.periodIndExpirationDate || null,
    sled_bbd: formData.sledBbd || null,

    // Tab 5: Planejamento (MRP)
    mrp_type: formData.mrpType || null,
    mrp_ctrler: formData.mrpCtrler || null,
    mrp_group: formData.mrpGroup || null,
    reorder_pt: formData.reorderPt || null,
    lotsizekey: formData.lotsizekey || null,
    minlotsize: formData.minlotsize || null,
    maxlotsize: formData.maxlotsize || null,
    fixed_lot: formData.fixedLot || null,
    round_val: formData.roundVal || null,
    serv_level: formData.servLevel || null,
    max_stock: formData.maxStock || null,
    safety_stk: formData.safetyStk || null,
    min_safety_stk: formData.minSafetyStk || null,
    covprofile: formData.covprofile || null,
    bwd_cons: formData.bwdCons || null,
    consummode: formData.consummode || null,
    fwd_cons: formData.fwdCons || null,
    replentime: formData.replentime || null,
    dep_req_id: formData.depReqId || null,
    plan_strgp: formData.planStrgp || null,

    // Tab 6: Produção
    proc_type: formData.procType || null,
    spproctype: formData.spproctype || null,
    backflush: formData.backflush || null,
    jit_relvt: formData.jitRelvt || null,
    bulk_mat: formData.bulkMat || null,
    batchentry: formData.batchentry || null,
    inhseprodt: formData.inhseprodt || null,
    plnd_delry: formData.plndDelry || null,
    gr_pr_time: formData.grPrTime || null,
    ppc_pl_cal: formData.ppcPlCal || null,
    sm_key: formData.smKey || null,
    assy_scrap: formData.assyScrap || null,
    comp_scrap: formData.compScrap || null,
    repmanprof: formData.repmanprof || null,
    rep_manuf: formData.repManuf || null,
    production_scheduler: formData.productionScheduler || null,
    prodprof: formData.prodprof || null,
    under_tol: formData.underTol || null,
    over_tol: formData.overTol || null,
    no_costing: formData.noCosting || null,
    serno_prof: formData.sernoProf || null,
    lot_size: formData.lotSize || null,
    specprocty: formData.specprocty || null,
    prt_usage: formData.prtUsage || null,
    ctrl_key: formData.ctrlKey || null,
    db_text: formData.dbText || null,

    // Tab 7: Armazenagem
    stge_loc: formData.stgeLoc || null,
    ctrl_code: formData.ctrlCode || null,
    stge_bin: formData.stgeBin || null,
    availcheck: formData.availcheck || null,
    trans_grp: formData.transGrp || null,
    loadinggrp: formData.loadinggrp || null,
    countryori: formData.countryori || null,
    profit_ctr: formData.profitCtr || null,
    sh_mat_typ: formData.shMatTyp || null,
    mat_cfop: formData.matCfop || null,
    sd_text: formData.sdText || null,
    iss_st_loc: formData.issStLoc || null,
    supply_area: formData.supplyArea || null,
    sloc_exprc: formData.slocExprc || null,

    // Tab 8: Sales Distribution (array)
    sales_distributions: formData.salesDistribution ? [{
      vkorg: formData.salesDistribution.vkorg || null,
      vtweg: formData.salesDistribution.vtweg || null,
      spart: formData.salesDistribution.spart || null,
      dwerk: formData.salesDistribution.dwerk || null,
      lgort: formData.salesDistribution.lgort || null,
      prctr: formData.salesDistribution.prctr || null,
      ktgrm: formData.salesDistribution.ktgrm || null,
      sales_unit: formData.salesDistribution.salesUnit || null,
      min_order: formData.salesDistribution.minOrder || null,
      min_dely: formData.salesDistribution.minDely || null,
      dely_unit: formData.salesDistribution.delyUnit || null,
      tax_type_1: formData.salesDistribution.taxType1 || null,
      taxclass_1: formData.salesDistribution.taxclass1 || null,
      matl_stats: formData.salesDistribution.matlStats || null,
      rebate_grp: formData.salesDistribution.rebateGrp || null,
      comm_group: formData.salesDistribution.commGroup || null,
      mat_pr_grp: formData.salesDistribution.matPrGrp || null,
      acct_assgt: formData.salesDistribution.acctAssgt || null,
      cash_disc: formData.salesDistribution.cashDisc || null,
      round_prof: formData.salesDistribution.roundProf || null,
    }] : [],

    // Tab 9: Controlling (array)
    controllings: formData.controlling ? [{
      bwkey: formData.controlling.bwkey || null,
      bwtar: formData.controlling.bwtar || null,
      mat_klass: formData.controlling.matKlass || null,
      val_area: formData.controlling.valArea || null,
      val_class: formData.controlling.valClass || null,
      price_ctrl: formData.controlling.priceCtrl || null,
      std_price: formData.controlling.stdPrice || null,
      price_unit: formData.controlling.priceUnit || null,
      moving_price: formData.controlling.movingPrice || null,
      price_date: formData.controlling.priceDate || null,
      ml_active: formData.controlling.mlActive || false,
      ml_settle: formData.controlling.mlSettle || false,
      origin_mat: formData.controlling.originMat || false,
      origin_group: formData.controlling.originGroup || null,
      overhead_grp: formData.controlling.overheadGrp || null,
      profit_ctr2: formData.controlling.profitCtr2 || null,
      qty_struct: formData.controlling.qtyStruct || false,
      in_house: formData.controlling.inHouse || false,
      mat_usage: formData.controlling.matUsage || null,
      plndprice1: formData.controlling.plndprice1 || null,
      plndprdate1: formData.controlling.plndprdate1 || null,
      plndprice2: formData.controlling.plndprice2 || null,
      plndprdate2: formData.controlling.plndprdate2 || null,
      plndprice3: formData.controlling.plndprice3 || null,
      plndprdate3: formData.controlling.plndprdate3 || null,
    }] : [],

    // Dados do sistema
    isActive: formData.isActive !== undefined ? formData.isActive : true,
  };
}

