// ----------------------------------------------------------------------
// Opções de Centros/Plantas para Materiais
// ----------------------------------------------------------------------

export const PLANT_OPTIONS = [
  { value: '0001', label: '0001 - Werk 0001' },
  { value: '0003', label: '0003 - Plant 0003 (is-ht-sw)' },
  { value: '1410', label: '1410 - Plant 1 BR' },
  { value: '1710', label: '1710 - Plant 1 US' },
  { value: '9999', label: '9999 - RM@FS' },
  { value: 'A001', label: 'A001 - COTRIJAL - NAO-ME-TOQUE' },
  { value: 'A002', label: 'A002 - COTRIJAL - COLORADO' },
  { value: 'A003', label: 'A003 - COTRIJAL - VICTOR GRAEFF' },
  { value: 'A005', label: 'A005 - COTRIJAL - TIO HUGO' },
  { value: 'A008', label: 'A008 - COTRIJAL - VISTA ALEGRE' },
  { value: 'A010', label: 'A010 - COTRIJAL - LAGOA DOS TRES' },
  { value: 'A011', label: 'A011 - COTRIJAL - CARAZINHO' },
  { value: 'A013', label: 'A013 - COTRIJAL - ALMIRANTE TAMANDARE' },
  { value: 'A015', label: 'A015 - COTRIJAL - SANTO ANTONIO DO' },
  { value: 'A018', label: 'A018 - COTRIJAL - CARAZINHO - CENTRO' },
  { value: 'A019', label: 'A019 - COTRIJAL - PINHEIRO MARCADO' },
  { value: 'A020', label: 'A020 - COTRIJAL - CARAZINHO - GLORIA' },
  { value: 'A021', label: 'A021 - COTRIJAL - XADREZ - COQUEIROS' },
  { value: 'A022', label: 'A022 - COTRIJAL - IGREJINHA' },
  { value: 'A023', label: 'A023 - COTRIJAL - LINHA JACUI' },
  { value: 'A024', label: 'A024 - COTRIJAL - SAO JOSE DA GLORIA' },
  { value: 'A026', label: 'A026 - COTRIJAL - SALDANHA MARINHO' },
  { value: 'A027', label: 'A027 - COTRIJAL - NICOLAU VERGUEIRO' },
  { value: 'A031', label: 'A031 - COTRIJAL - COLORADO DISTRITO' },
  { value: 'A032', label: 'A032 - COTRIJAL - ENCRUZILHADA MULLER' },
  { value: 'A033', label: 'A033 - COTRIJAL - ARROIO BONITO' },
  { value: 'A034', label: 'A034 - COTRIJAL - SAO JOSE DO CENTRO' },
  { value: 'A035', label: 'A035 - COTRIJAL - PASSO FUNDO' },
  { value: 'A037', label: 'A037 - COTRIJAL - ERNESTINA' },
  { value: 'A039', label: 'A039 - COTRIJAL - BOM SUCESSO' },
  { value: 'A042', label: 'A042 - COTRIJAL - TRES PASSOS' },
  { value: 'A043', label: 'A043 - COTRIJAL - CARAZINHO' },
  { value: 'A044', label: 'A044 - COTRIJAL - BELA VISTA' },
  { value: 'A046', label: 'A046 - COTRIJAL - MATO CASTELHANO' },
  { value: 'A052', label: 'A052 - COTRIJAL - ESMERALDA' },
  { value: 'A053', label: 'A053 - COTRIJAL - COXILHA' },
  { value: 'A055', label: 'A055 - COTRIJAL - ESMERALDA ANEXO' },
  { value: 'A056', label: 'A056 - COTRIJAL - PINHAL DA SERRA' },
  { value: 'A057', label: 'A057 - COTRIJAL - ESTACAO' },
  { value: 'A058', label: 'A058 - COTRIJAL - CLEMENTE ARGOLO' },
  { value: 'A060', label: 'A060 - COTRIJAL - ESQUINA BOM JESUS' },
  { value: 'A062', label: 'A062 - COTRIJAL - SERTAO' },
  { value: 'A063', label: 'A063 - COTRIJAL - CAPO-ERE' },
  { value: 'A064', label: 'A064 - COTRIJAL - VILA LANGARO' },
  { value: 'A065', label: 'A065 - COTRIJAL - VALINHOS' },
  { value: 'A066', label: 'A066 - COTRIJAL - LAGOA VERMELHA' },
  { value: 'A067', label: 'A067 - COTRIJAL - MUITOS CAPOES' },
  { value: 'A068', label: 'A068 - COTRIJAL - ESMERALDA' },
  { value: 'A069', label: 'A069 - COTRIJAL - RIO TELHA' },
  { value: 'A070', label: 'A070 - COTRIJAL - TRES PINHEIROS' },
  { value: 'A071', label: 'A071 - COTRIJAL - TAPEJARA' },
  { value: 'A072', label: 'A072 - COTRIJAL - CHARRUA' },
  { value: 'A074', label: 'A074 - COTRIJAL - AGUA SANTA' },
  { value: 'A075', label: 'A075 - COTRIJAL - CAPAO BONITO DO SUL' },
  { value: 'A077', label: 'A077 - COTRIJAL -LAGOA VERMELHA' },
  { value: 'A098', label: 'A098 - COTRIJAL - CRUZALTINHA' },
  { value: 'A100', label: 'A100 - COTRIJAL - CRUZ ALTA' },
  { value: 'A104', label: 'A104 - COTRIJAL - ENCRUZILHADA DO SUL' },
  { value: 'A105', label: 'A105 - COTRIJAL - PANTANO GRANDE' },
  { value: 'A106', label: 'A106 - COTRIJAL - VACARIA' },
  { value: 'A107', label: 'A107 - COTRIJAL - CASCA' },
  { value: 'A109', label: 'A109 - COTRIJAL - SANTO ANTONIO DO' },
  { value: 'A110', label: 'A110 - COTRIJAL - SOLEDADE LINHA' },
  { value: 'A111', label: 'A111 - COTRIJAL - SOLEDADE PONTAO BOA' },
  { value: 'A112', label: 'A112 - COTRIJAL - SOLEDADE BOTUCARAI' },
  { value: 'A114', label: 'A114 - COTRIJAL - MORMACO' },
  { value: 'A115', label: 'A115 - COTRIJAL - JACUIZINHO' },
  { value: 'A116', label: 'A116 - COTRIJAL - LAGOAO' },
  { value: 'A117', label: 'A117 - COTRIJAL - BARROS CASSAL' },
  { value: 'A118', label: 'A118 - COTRIJAL - BARROS CASSAL CERCA' },
  { value: 'A119', label: 'A119 - COTRIJAL - VERA CRUZ' },
  { value: 'A120', label: 'A120 - COTRIJAL - RIO PARDO' },
  { value: 'A121', label: 'A121 - COTRIJAL - CANDELARIA PINHEIRO' },
  { value: 'A122', label: 'A122 - COTRIJAL - CANDELARIA' },
  { value: 'A123', label: 'A123 - COTRIJAL - SOLEDADE DEFENSIVOS' },
  { value: 'A124', label: 'A124 - COTRIJAL - IBIRAPUITA' },
  { value: 'A125', label: 'A125 - COTRIJAL - CAMARGO' },
  { value: 'A126', label: 'A126 - COTRIJAL - ITAPUCA' },
  { value: 'A143', label: 'A143 - COTRIJAL - TUNAS' },
  { value: 'A145', label: 'A145 - COTRIJAL - SOLEDADE PONTÃO DA' },
  { value: 'A146', label: 'A146 - COTRIJAL - FONTOURA XAVIER' },
  { value: 'A147', label: 'A147 - COTRIJAL - ARVOREZINHA' },
  { value: 'A148', label: 'A148 - COTRIJAL - VILA MARIA LINHA A.' },
  { value: 'A151', label: 'A151 - COTRIJAL - NOVA ALVORADA' },
  { value: 'A156', label: 'A156 - COTRIJAL - RIO PARDO ALBARDAO' },
  { value: 'AFC1', label: 'AFC1 - TRANSPORTES COTRIJAL' },
  { value: 'E028', label: 'E028 - COTRIJAL - EXPODIRETO' },
  { value: 'F029', label: 'F029 - NAO-ME-TOQUE - FABRICA RACAO' },
  { value: 'IT01', label: 'IT01 - Plant 1 BR - Em transito' },
  { value: 'L049', label: 'L049 - NAO-ME-TOQUE - LOJA' },
  { value: 'L050', label: 'L050 - SALDANHA MARINHO - LOJA' },
  { value: 'L051', label: 'L051 - NAO-ME-TOQUE - CD LOJA' },
  { value: 'L078', label: 'L078 - TAPEJARA - LOJA' },
  { value: 'L079', label: 'L079 - COXILHA - LOJA' },
  { value: 'L080', label: 'L080 - PASSO FUNDO - LOJA' },
  { value: 'L081', label: 'L081 - COLORADO - LOJA' },
  { value: 'L082', label: 'L082 - ESMERALDA - LOJA' },
  { value: 'L083', label: 'L083 - ERNESTINA - LOJA' },
  { value: 'L084', label: 'L084 - TIO HUGO - LOJA' },
  { value: 'L085', label: 'L085 - NICOLAU VERGUEIRO - LOJA' },
  { value: 'L086', label: 'L086 - SANTO ANTONIO DO PLANALTO -' },
  { value: 'L087', label: 'L087 - MATO CASTELHANO - LOJA' },
  { value: 'L088', label: 'L088 - LAGOA DOS TRES CANTOS - LOJA' },
  { value: 'L089', label: 'L089 - VISTA ALEGRE - LOJA' },
  { value: 'L090', label: 'L090 - CARAZINHO -  LOJA' },
  { value: 'L091', label: 'L091 - ALMIRANTE TAMANDARE DO SUL -' },
  { value: 'L092', label: 'L092 - IGREJINHA - LOJA' },
  { value: 'L093', label: 'L093 - VICTOR GRAEFF - LOJA' },
  { value: 'L094', label: 'L094 - XADREZ - LOJA' },
  { value: 'L096', label: 'L096 - CAPAO BONITO DO SUL - LOJA' },
  { value: 'L099', label: 'L099 - ESTACAO - LOJA' },
  { value: 'L102', label: 'L102 - PASSO FUNDO PETROPOLIS - LOJA' },
  { value: 'L103', label: 'L103 - AGUA SANTA - LOJA' },
  { value: 'L135', label: 'L135 - SOLEDADE - LOJA' },
  { value: 'L136', label: 'L136 - BARROS CASSAL - LOJA' },
  { value: 'L138', label: 'L138 - FONTOURA XAVIER - LOJA' },
  { value: 'L140', label: 'L140 - IBIRAPUITA - LOJA' },
  { value: 'L141', label: 'L141 - LAGOAO - LOJA' },
  { value: 'L142', label: 'L142 - RIO PARDO - LOJA' },
  { value: 'L150', label: 'L150 - NOVA ALVORADA - LOJA' },
  { value: 'L152', label: 'L152 - MARAU - LOJA' },
  { value: 'L155', label: 'L155 - MORMACO - LOJA' },
  { value: 'S006', label: 'S006 - NAO-ME-TOQUE - SUPER' },
  { value: 'S007', label: 'S007 - VICTOR GRAEFF - SUPER' },
  { value: 'S009', label: 'S009 - COLORADO - SUPER' },
  { value: 'S014', label: 'S014 - TIO HUGO - SUPER' },
  { value: 'S017', label: 'S017 - STO ANTONIO PLANALTO - SUPER' },
  { value: 'S038', label: 'S038 - CD MERCADO- NAO-ME-TOQUE' },
  { value: 'S040', label: 'S040 - LAGOA TRES CANTOS - SUPER' },
  { value: 'S041', label: 'S041 - NAO-ME-TOQUE - SUPER CENTRO' },
  { value: 'S047', label: 'S047 - COQUEIROS DO SUL - SUPER' },
  { value: 'S059', label: 'S059 - NAO-ME-TOQUE - ATACADO' },
  { value: 'S095', label: 'S095 - LAGOA VERMELHA - SUPER' },
  { value: 'S127', label: 'S127 - FONTOURA XAVIER - SUPER' },
  { value: 'S129', label: 'S129 - SOLEDADE - SUPER' },
  { value: 'S130', label: 'S130 - SOLEDADE - SUPER CENTRO' },
  { value: 'S132', label: 'S132 - TUNAS - SUPER' },
  { value: 'S144', label: 'S144 - IBIRAPUITA - SUPER' },
  { value: 'S153', label: 'S153 - MARAU - SUPER' },
  { value: 'T097', label: 'T097 - COTRIJAL - TRR' },
  { value: 'TR01', label: 'TR01 - TRANSPORTES COTRIJAL' },
  { value: 'TR02', label: 'TR02 - TRANSPORTES COTRIJAL' },
  { value: 'TR03', label: 'TR03 - TRANSPORTES COTRIJAL' },
  { value: 'U012', label: 'U012 - COTRIJAL - UBS' },
  { value: 'V101', label: 'V101 - COTRIJAL -  VIVEIRO' },
];

// Função para buscar centros por termo
export const searchPlantOptions = (searchTerm) => {
  if (!searchTerm) return PLANT_OPTIONS;
  
  const term = searchTerm.toLowerCase();
  return PLANT_OPTIONS.filter(option => 
    option.value.toLowerCase().includes(term) || 
    option.label.toLowerCase().includes(term)
  );
};

// Função para obter label do centro pelo valor
export const getPlantLabel = (value) => {
  const option = PLANT_OPTIONS.find(opt => opt.value === value);
  return option ? option.label : value;
};
