// Unidades de medida comuns (SAP / materiais)
// Formato: { value: código, label: descrição }

export const UNIT_OPTIONS = [
  { value: 'KG', label: 'Quilograma' },
  { value: 'G', label: 'Grama' },
  { value: 'T', label: 'Tonelada' },
  { value: 'UN', label: 'Unidade' },
  { value: 'PC', label: 'Peça' },
  { value: 'PÇ', label: 'Peça' },
  { value: 'M', label: 'Metro' },
  { value: 'M2', label: 'Metro quadrado' },
  { value: 'M3', label: 'Metro cúbico' },
  { value: 'L', label: 'Litro' },
  { value: 'ML', label: 'Mililitro' },
  { value: 'CX', label: 'Caixa' },
  { value: 'PT', label: 'Pacote' },
  { value: 'FD', label: 'Fardo' },
  { value: 'SC', label: 'Saco' },
  { value: 'TB', label: 'Tubo' },
  { value: 'LT', label: 'Lata' },
  { value: 'GL', label: 'Galão' },
  { value: 'PCT', label: 'Pacote' },
  { value: 'KIT', label: 'Kit' },
  { value: 'PAR', label: 'Par' },
  { value: 'DZ', label: 'Dúzia' },
  { value: 'JR', label: 'Jogo' },
  { value: 'RL', label: 'Rolo' },
  { value: 'MT', label: 'Metro linear' },
  { value: 'CM', label: 'Centímetro' },
  { value: 'MM', label: 'Milímetro' },
  { value: 'KM', label: 'Quilômetro' },
  { value: 'HA', label: 'Hectare' },
  { value: 'HR', label: 'Hora' },
  { value: 'MIN', label: 'Minuto' },
  { value: 'DIA', label: 'Dia' },
  { value: 'SEM', label: 'Semana' },
  { value: 'MES', label: 'Mês' },
  { value: 'ANO', label: 'Ano' },
  { value: 'ST', label: 'Conjunto' },
  { value: 'EA', label: 'Cada' },
  { value: 'BAL', label: 'Bale' },
  { value: 'BOL', label: 'Bobina' },
  { value: 'BAR', label: 'Barra' },
  { value: 'BAT', label: 'Batch' },
  { value: 'BTL', label: 'Garrafa' },
  { value: 'CAN', label: 'Cano' },
  { value: 'CAR', label: 'Carga' },
  { value: 'CEN', label: 'Cento' },
  { value: 'CIL', label: 'Cilindro' },
  { value: 'CON', label: 'Container' },
  { value: 'DIS', label: 'Display' },
  { value: 'EMB', label: 'Embalagem' },
  { value: 'FAR', label: 'Fardo' },
  { value: 'FOL', label: 'Folha' },
  { value: 'GRP', label: 'Grupo' },
  { value: 'LBA', label: 'Libra' },
  { value: 'MAL', label: 'Maleta' },
  { value: 'PAL', label: 'Palete' },
  { value: 'PLA', label: 'Placa' },
  { value: 'RES', label: 'Resma' },
  { value: 'TAN', label: 'Tanque' },
  { value: 'TON', label: 'Tonelada' },
  { value: 'VD', label: 'Vidro' },
  { value: 'BX', label: 'Box' },
  { value: 'BAG', label: 'Bolsa' },
  { value: 'BOT', label: 'Botijão' },
  { value: 'CJ', label: 'Conjunto' },
  { value: 'OZ', label: 'Onça' },
  { value: 'LB', label: 'Libra' },
  { value: 'CL', label: 'Centilitro' },
  { value: 'DL', label: 'Decilitro' },
  { value: 'HL', label: 'Hectolitro' },
  { value: 'QT', label: 'Quilate' },
  { value: 'SM', label: 'Sqm' },
  { value: 'SF', label: 'Square foot' },
  { value: 'CF', label: 'Cubic foot' },
  { value: 'IN', label: 'Polegada' },
  { value: 'FT', label: 'Pé' },
  { value: 'YD', label: 'Jarda' },
  { value: 'GLL', label: 'Galão (US)' },
  { value: 'BBL', label: 'Barril' },
  { value: 'PR', label: 'Par' },
  { value: 'SET', label: 'Set' },
  { value: 'PAIR', label: 'Par' },
  { value: 'DOZ', label: 'Dúzia' },
  { value: 'GRO', label: 'Grosa' },
  { value: 'TRIP', label: 'Triagem' },
  { value: 'SERV', label: 'Serviço' },
  { value: 'CONS', label: 'Consumo' },
].sort((a, b) => a.value.localeCompare(b.value));
